// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: ref.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Refereses with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Refereses) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Refereses with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ReferesesMultiError, or nil
// if none found.
func (m *Refereses) ValidateAll() error {
	return m.validate(true)
}

func (m *Refereses) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for VendorBol

	// no validation rules for Bol

	// no validation rules for VendorReferenceId

	// no validation rules for PickupNo

	// no validation rules for InvoiceNo

	// no validation rules for VendorInvoiceNo

	if len(errors) > 0 {
		return ReferesesMultiError(errors)
	}
	return nil
}

// ReferesesMultiError is an error wrapping multiple validation errors returned
// by Refereses.ValidateAll() if the designated constraints aren't met.
type ReferesesMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReferesesMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReferesesMultiError) AllErrors() []error { return m }

// ReferesesValidationError is the validation error returned by
// Refereses.Validate if the designated constraints aren't met.
type ReferesesValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReferesesValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReferesesValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReferesesValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReferesesValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReferesesValidationError) ErrorName() string { return "ReferesesValidationError" }

// Error satisfies the builtin error interface
func (e ReferesesValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRefereses.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReferesesValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReferesesValidationError{}
